version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/data/:/var/lib/clickhouse/
      - ./clickhouse/logs/:/var/log/clickhouse-server/
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: "primoart"
      CLICKHOUSE_USER: "primo"
      CLICKHOUSE_PASSWORD: "primo"

  postgres:
    image: postgres:13.3
    container_name: postgres-primoart
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "primoart"
      POSTGRES_USER: "primo"
      POSTGRES_PASSWORD: "primo"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U primo -d primoart"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  uvicorn:
    build:
      context: .
      dockerfile: Dockerfile.uvicorn
    volumes:
      - ./api:/api
      - ./mvp:/mvp
      - ./logs:/logs
      - ./screenshots:/screenshots
      - ./orm:/orm
      - ./config.json:/config.json
    command: "python3 -m api.api_main"
    ports:
      - "8000:8000"
    container_name: uvicorn-api
    restart: always
